config/routes.rb
Rails.application.routes.draw do


   devise_for :authors,controllers: { registrations: "registrations"}
   # resources :authors do
   #   member do
   #        get :following, :followers
   #     end
   #   end
   root to: "blog/posts#index"


   namespace :authors do
     get '/account' => 'accounts#edit', as: :account
     put '/info' => "accounts#update_info", as: :info
     put '/change_password' => 'accounts#change_password', as: :change_password
     get '/changepassword'=>'accounts#password', as: :password

     resources :authors do
       member do
         get :following, :followers
       end
     end
     resources :posts do
       put 'publish' => 'posts#publish', on: :member
       put 'unpublish' => 'posts#unpublish', on: :member
     end
   end


  scope module: 'blog' do
    get 'about'=>"pages#about", as: :about
    get 'contact'=>"pages#contact", as: :contact
    get 'posts' =>'posts#index', as: :posts
    get 'posts/:id' =>'posts#show', as: :post
    resources :posts do
      get 'author' => 'posts#author', on: :member
      get 'following'=>'posts#following', on: :member
      get 'followers' =>'posts#followers', on: :member
    end


    resources :relationships,       only: [:create, :destroy]

  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :datetime
#

class Post < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags

  extend FriendlyId
  friendly_id :title, use: :slugged
  scope :most_recent, -> { order(published_at: :desc) }
  scope :published, -> {where(published: true)}
  scope :recent_paginate, -> (page) {most_recent.paginate(page: page, :per_page => 6) }
  scope :with_tage,->(tag){tagged_with(tag) if tag.present?}

  scope :list_for, ->(page,tag) do
      @posts = recent_paginate(page).with_tage(tag)
  end

  belongs_to :author, optional: true, dependent:   :destroy

  def should_generate_new_friendly_id?
     title_changed?
  end
  def display_day
    if published_at.present?
   "Published #{published_at.strftime('%-b %-d,%Y')}"
    else
      "Not published Yet."
      end
  end
  end

app/controllers/authors/posts_controller.rb
module Authors

  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
      # @image =current_author.image_file_name
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def publish
      @post.update(published: true)
      @post.update(published_at: Time.now)

      redirect_to authors_posts_url
    end
    def unpublish
      @post.update(published: false)
      @post.update(published_at: nil)

      redirect_to authors_posts_url

    end

    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description,:a_name,:banner_image_url, :tag_list)
    end

  end



end

app/controllers/blog/pages_controller.rb
module Blog
class PagesController < BlogController
  def about

  end
  def contact

  end
end
  end

app/controllers/blog/posts_controller.rb
module Blog

   class PostsController < BlogController
     # before_action :set_test, only: [:author]

     # GET /posts
      # GET /posts.json
      def index
       @posts=storage.list_for(params[:page],params[:tag])
        #  user = Post.find_by  (params[:author_id])
        # @author = user.author

      end


      # GET /posts/1
      # GET /posts/1.json
      def show
        @post = storage.friendly.find(params[:id])

      end

      def author
        @author = Author.find(params[:id])
        @posts=@author.posts
      end


      def following
        @title = "Following"
        @author  = Author.find(params[:id])
        @authors = @author.following
      end

      def followers
        @title = "Followers"
        @author = Author.find(params[:id])
        @authors = @author.followers.paginate(page: params[:page])
        # render 'show_follow'
      end


      private
     def storage
       Post.published
     end
     # def set_test
     #   @author = Author.find(params[:id])
     # end
   end


end

app/controllers/blog/relationships_controller.rb
module Blog

  class RelationshipsController<BlogController


    def create
      author = Author.find(params[:followed_id])
      current_author.follow(author)
      redirect_to request.referrer
    end

    def destroy
      author = Relationship.find(params[:id]).followed
      current_author.unfollow(author)
      redirect_to request.referrer
    end


  end



end

app/controllers/blog_controller.rb
class BlogController < ActionController::Base
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/posts/_post.html.erb
<div class="col-sm-8 col-lg-4">
  <div class="card">
      <div class="card-topper" style='background-image: url(<%=post.banner_image_url %>);'></div>


    <div class="card-block">
      <h4 class="card-title"><%= link_to truncate(post.title,length: 70) ,post %></h4>
      <p class="tags" ><%= raw post.tags.map { |t| link_to t.name, posts_path(tag: t.name) }.join(', ') %></p>
      <% if author_signed_in? %>
        <%= link_to  "Author : #{post.a_name}",author_post_path(post.author_id) %>
      <%end%>
      <p class="published-date"><%=post.display_day%></p>



      <%= link_to post  do%>
        <p class="card-text"><%= truncate(post.description,length: 90) %></p>
      <% end %>


    </div>
  </div>
</div>

app/views/blog/posts/author.html.erb
        <div class="container" >
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">About <%=@author.f_name %> </h4>
      </div>
      <div class="modal-body">

        <center>

          <%= image_tag(@author.avatar.url,class:"img-thumbnail",name:"aboutme", width:"140" ,height:"140" ,border:"0" ,class:"img-circle",alt:"")  %>

          <h3 class="media-heading"><%=@author.f_name %>&nbsp;<%=@author.l_name%><small><%=@author.country%></small></h3>
          <span><strong>Skills: </strong></span>
          <h6 class="label label-warning"><%=@author.profession%></h6>

        </center>
        <br>
<center>
        <div class="col-xs-12 col-sm-4 emphasis">
          <h2><strong> <%=@author.following.count %></strong></h2>
          <p><small><%=link_to "Following:", following_post_path(@author)%></small></p>

<!--          <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow </button>-->
          <% if current_author.id != @author.id %>
            <%if current_author.following?(@author)%>

              <%= form_for(current_author.active_relationships.find_by(followed_id: @author.id),
                           html: { method: :delete }) do |f| %>
                <%= f.submit "Unfollow", class: "btn btn-success btn-block"  %>

               <%end%>
            <%else%>
              <%= form_for(current_author.active_relationships.build) do |f| %>
                <div><%= hidden_field_tag :followed_id, @author.id %></div>
                <%= f.submit "Follow", class: "btn btn-success btn-block"%>

              <%end%>
            <% end %>
          <%end%>

        </div>
        <div class="col-xs-12 col-sm-4 emphasis">
          <h2><strong><%=@author.followers.count %></strong></h2>
          <p><small><%=link_to "Followers:", followers_post_path(@author)%></small></p>
          <% if current_author.id != @author.id %>

        <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button>
            <%end%>
        </div>

        <div class="col-xs-12 col-sm-4 emphasis">
          <h2><strong><%=@author.posts.count%></strong></h2>
          <p><small>Posts</small></p>
          <% if current_author.id != @author.id %>

          <div class="btn-group dropup btn-block" >
            <button type="button" class="btn btn-primary " style="height:38px;width:260px"><span class="fa fa-gear"></span> Options </button>
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <%end%>
            <br><br><br>


            <ul class="dropdown-menu text-left" role="menu">
              <li ><a href="#"><span class="fa fa-envelope pull-right"></span> Send an email   </a></li>
              <li class="divider"></li>

              <li ><a href="#"><span class="fa fa-list pull-right"></span> Remove from a list &nbsp;&nbsp;&nbsp; </a></li>
              <li class="divider"></li>

              <li><a href="#"><span class="fa fa-warning pull-right"></span>Report this user for spam</a></li>
            </ul>
          </div>
        </div>
</center>

        <p class="text-left"><br><br><strong>Bio: </strong><br>
<%= @author.bio%>
          <br>
      </div>



      <br>
      <br>
      <div class="row">
        <%= render @posts%>
      </div>

        </div>                          

    <!--      <div class="modal-footer">-->
    <!--        <center>-->
    <!--          <button type="button" class="btn btn-default" data-dismiss="modal">I've heard enough about Joe</button>-->
    <!--        </center>-->
    <!--      </div>-->

app/views/blog/posts/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="media">
        <% @authors.each do |author| %>

          <div class="media-left">
              <%= image_tag(author.avatar.url,class:"img-thumbnail",name:"aboutme", width:"140" ,height:"140" ,border:"0" ,class:"img-circle",alt:"") %>

          </div>
          <div class="media-body">
            <h4 class="media-heading"> <%=link_to "#{author.name}",author_post_path(author.id)%></h4>
            <%#=author.name%>
            <%=truncate(author.bio,length: 120)%>
          </div>

          </div>

          </div>
        <% end %>
        </div>
</div>

app/views/blog/posts/following.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="media">
        <% @authors.each do |author| %>

          <div class="media-left">
            <%= image_tag(author.avatar.url,class:"img-thumbnail",name:"aboutme", width:"140" ,height:"140" ,border:"0" ,class:"img-circle",alt:"") %>

          </div>
          <div class="media-body">
            <h4 class="media-heading"> <%=link_to "#{author.name}",author_post_path(author.id)%></h4>
            <%=truncate(author.bio,length: 120)%>
          </div>
          </div>

          </div>
        <% end %>
        </div>
</div>

app/views/blog/posts/index.html.erb
<% provide(:page_title,"All posts")%>
<% provide(:blog_active,"active")%>


<div class="row">
  <%= render @posts%>
</div>
<div class="apple_pagination">
<%= will_paginate @posts,:contaniner => false%>
</div>

app/views/blog/posts/show.html.erb
<%provide(:page_title,@post.title)%>
<% provide(:blog_active,"active")%>
<div class="row">
  <div class="col-md-10  col-lg-12  text-xs-center">
    <%#= image_tag @image.image_file_name.url(:medium)%>
    <h1><%= @post.title%></h1>
  <h6><%=@post.display_day%></h6>
  <%=@post.body.html_safe%>
    <div id="disqus_thread"></div>

    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <br><br><br><br>

  </div>

</div>


<script>

    // /**
    //  *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    //  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    // /
    <%# binding.pry %>

    var disqus_config = function () {
    this.page.url = '<%= request.original_url %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.slug %>>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://problog-3.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>