config/routes.rb
Rails.application.routes.draw do


   devise_for :authors,controllers: { registrations: "registrations"}
   # resources :authors do
   #   member do
   #        get :following, :followers
   #     end
   #   end
   root to: "blog/posts#index"


   namespace :authors do
     get '/account' => 'accounts#edit', as: :account
     put '/info' => "accounts#update_info", as: :info
     put '/change_password' => 'accounts#change_password', as: :change_password
     get '/changepassword'=>'accounts#password', as: :password

     resources :authors do
       member do
         get :following, :followers
       end
     end
     resources :posts do
       put 'publish' => 'posts#publish', on: :member
       put 'unpublish' => 'posts#unpublish', on: :member
     end
   end


  scope module: 'blog' do
    get 'about'=>"pages#about", as: :about
    get 'contact'=>"pages#contact", as: :contact
    get 'posts' =>'posts#index', as: :posts
    get 'posts/:id' =>'posts#show', as: :post
    resources :posts do
      get 'author' => 'posts#author', on: :member
      get 'following'=>'posts#following', on: :member
      get 'followers' =>'posts#followers', on: :member
    end


    resources :relationships,       only: [:create, :destroy]

  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable,:timeoutable,
         :recoverable, :rememberable,:registerable, :trackable, :validatable

  has_many :posts
  has_many :active_relationships, class_name:  "Relationship",
           foreign_key: "follower_id",
           dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
           foreign_key: "followed_id",
           dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  validates_uniqueness_of :name,on: :create

  validates_presence_of :name, on: :update
  # validates_presence_of :avatar, on: :update

  def change_password(attr)
     update(password: attr[:new_password],password_confirmation: attr[:new_password_confirmation])
  end



  def follow(other_author)
    following << other_author
  end

  # Unfollows a user.
  def unfollow(other_author)
    following.delete(other_author)
  end

  # Returns true if the current user is following the other user.
  def following?(other_author)
    following.include?(other_author)
  end


end

app/controllers/author_controller.rb
class AuthorController < ActionController::Base


  before_action :authenticate_author!


end

app/controllers/authors/accounts_controller.rb
module Authors

  class AccountsController < AuthorController
    def edit

    end

    # def update_info
    #   if current_author.update(author_info_params)
    #     flash[:success] = 'Successfully saved info.'
    #   else
    #     flash[:danger] = current_author.display_error_messages
    #   end
    #   redirect_to authors_account_path
    # end
    def change_password
      author=current_author
      if author.valid_password?(author_password_params[:current_password])

        if author.change_password(author_password_params)
          sign_in(author,bypass: true)
           flash[:success] = 'Successfully changed password.'

         else
           flash[:danger] = author.display_error_messages

         end

      else
        flash[:danger] = "current password was incorrect."
      end
      redirect_to authors_password_path

    end
    private
    # def author_info_params
    #   params.require(:author).permit(:avatar,:name,:email,:bio)
    # end
    def author_password_params
    params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end
  end


end

app/controllers/authors/posts_controller.rb
module Authors

  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
      # @image =current_author.image_file_name
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def publish
      @post.update(published: true)
      @post.update(published_at: Time.now)

      redirect_to authors_posts_url
    end
    def unpublish
      @post.update(published: false)
      @post.update(published_at: nil)

      redirect_to authors_posts_url

    end

    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description,:a_name,:banner_image_url, :tag_list)
    end

  end



end

app/views/authors/accounts/password.html.erb
<div class="container", style="alignment: center">

<%= form_tag authors_change_password_path, method: :put do %>
  <%= fields_for :author do |f| %>

    <div class="container bootstrap snippet">
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-7 col-md-offset-2">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span class="glyphicon glyphicon-th"></span>
          Change password
        </h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6 separator social-login-box"> <br>
<!--            <img alt="" class="img-thumbnail" src="https://bootdey.com/img/Content/avatar/avatar1.png">-->
            <%= image_tag(current_author.avatar.url,class:"img-thumbnail",alt:"") if current_author.avatar? %>

          </div>
          <div style="margin-top:80px;" class="col-xs-6 col-sm-6 col-md-6 login-box">
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :current_password, class: 'form-control' ,placeholder:"Current Password"%>

              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-log-in"></span></div>
                <%= f.password_field :new_password, class: 'form-control' ,placeholder: "New Password"%>

              </div>
            </div>

            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :new_password_confirmation, class: 'form-control',placeholder: "new_password_confirmation" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6"></div>
          <div class="col-xs-6 col-sm-6 col-md-6">

            <%= f.submit "Change password", class: 'btn btn-success' %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <% end %>
  </div>
<% end %>
</div>