config/routes.rb
Rails.application.routes.draw do


   devise_for :authors,controllers: { registrations: "registrations"}
   # resources :authors do
   #   member do
   #        get :following, :followers
   #     end
   #   end
   root to: "blog/posts#index"


   namespace :authors do
     get '/account' => 'accounts#edit', as: :account
     put '/info' => "accounts#update_info", as: :info
     put '/change_password' => 'accounts#change_password', as: :change_password
     get '/changepassword'=>'accounts#password', as: :password

     resources :authors do
       member do
         get :following, :followers
       end
     end
     resources :posts do
       put 'publish' => 'posts#publish', on: :member
       put 'unpublish' => 'posts#unpublish', on: :member
     end
   end


  scope module: 'blog' do
    get 'about'=>"pages#about", as: :about
    get 'contact'=>"pages#contact", as: :contact
    get 'posts' =>'posts#index', as: :posts
    get 'posts/:id' =>'posts#show', as: :post
    resources :posts do
      get 'author' => 'posts#author', on: :member
      get 'following'=>'posts#following', on: :member
      get 'followers' =>'posts#followers', on: :member
    end


    resources :relationships,       only: [:create, :destroy]

  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>

    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"
             style="right: 21px;">
        <span aria-hidden="true">&times;</span>
      </button>
      <% object.errors.full_messages.each do |msg| %>
        <strong><%=msg%></strong>
        <% end %>
    </div>
<% end %>



<%# if flash.any?%>
  <%# flash.keys.each do |key|%>
<!--    <div class="alert alert-<%#= key.to_s %> alert alert-dismissible" role="alert">-->
<!--      <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--        <span aria-hidden="true">&times;</span>-->
<!--      </button>-->
<!--      <strong><%#= flash[key]%></strong>-->
<!--    </div>-->
  <%#end%>
<%#end%>

<%#= yield %>

app/views/layouts/_navbar.html.erb
<header>
  <nav id='cssmenu'>
    <br>
      <%#= link_to( image_tag("logo1.png") , image_path( "logo1.png"))  %>

      <%= link_to root_path do %>
        <%= image_tag "logo1.png" ,class:"logo"%>
      <% end %>

    <div id="head-mobile"></div>
    <div class="button"></div>
    <ul>
      <li class='<%= current_class?(root_path) %>'><%= link_to 'HOME', root_path %></li>
      <li class="<%= current_class?(about_path) %>"> <%= link_to 'ABOUT', about_path %></li>
      <li class='<%= current_class?(contact_path) %>'><%= link_to 'CONTACT', contact_path %></li>
<!--      <li><a href='#'>VIDEO</a></li>-->
      <li><a href='#'>GALLERY</a></li>

      <% if author_signed_in? %>
<!--        glyphicon glyphicon-plus-->

        <li><a href='#'>AUTHOR</a>
          <ul>
            <li> <%= link_to 'Your posts', authors_posts_path %></li>
            <li class="sub-menu"><a href='#'>Account</a>
              <ul>
                <li><%= link_to 'Edit Profile', edit_author_registration_path %></li>
                <li><%= link_to 'Change Password',authors_password_path %></li>
              </ul>
            </li>
            <li> <%= link_to 'Logout', destroy_author_session_path, method: :delete %></li>

          </ul>
        <li class="round-image-50",> <%= image_tag(current_author.avatar.url)  %></li>

        </li>
      <%else%>

        <li><%= link_to 'LOG IN', new_author_session_path%>
        </li>
      <%end%>

    </ul>
  </nav>
</header>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:page_title) %> |ProBlog</title>

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <script>

      (function($) {
          $.fn.menumaker = function(options) {
              var cssmenu = $(this), settings = $.extend({
                  format: "dropdown",
                  sticky: false
              }, options);
              return this.each(function() {
                  $(this).find(".button").on('click', function(){
                      $(this).toggleClass('menu-opened');
                      var mainmenu = $(this).next('ul');
                      if (mainmenu.hasClass('open')) {
                          mainmenu.slideToggle().removeClass('open');
                      }
                      else {
                          mainmenu.slideToggle().addClass('open');
                          if (settings.format === "dropdown") {
                              mainmenu.find('ul').show();
                          }
                      }
                  });
                  cssmenu.find('li ul').parent().addClass('has-sub');
                  multiTg = function() {
                      cssmenu.find(".has-sub").prepend('<span class="submenu-button"></span>');
                      cssmenu.find('.submenu-button').on('click', function() {
                          $(this).toggleClass('submenu-opened');
                          if ($(this).siblings('ul').hasClass('open')) {
                              $(this).siblings('ul').removeClass('open').slideToggle();
                          }
                          else {
                              $(this).siblings('ul').addClass('open').slideToggle();
                          }
                      });
                  };
                  if (settings.format === 'multitoggle') multiTg();
                  else cssmenu.addClass('dropdown');
                  if (settings.sticky === true) cssmenu.css('position', 'fixed');
                  resizeFix = function() {
                      var mediasize = 1000;
                      if ($( window ).width() > mediasize) {
                          cssmenu.find('ul').show();
                      }
                      if ($(window).width() <= mediasize) {
                          cssmenu.find('ul').hide().removeClass('open');
                      }
                  };
                  resizeFix();
                  return $(window).on('resize', resizeFix);
              });
          };
      })(jQuery);

      (function($){
          $(document).ready(function(){
              $("#cssmenu").menumaker({
                  format: "multitoggle"
              });
          });
      })(jQuery);


  </script>
  </head>

<body>
<%=render 'layouts/navbar'%>
<div class="container <%=controller_name %> <%= action_name %>">

  <% if flash.any?%>
    <% flash.keys.each do |key|%>
      <div class="alert alert-<%= key.to_s %> alert alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong><%= flash[key]%></strong>
      </div>
    <%end%>
  <%end%>

  <%= yield %>

</div>
</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:page_title) %> |ProBlog</title>


<!--  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<!--  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->
<!--  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
   <%= csrf_meta_tags %>



  <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700|Montserrat:300,400,700" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
  <script>

      (function($) {
          $.fn.menumaker = function(options) {
              var cssmenu = $(this), settings = $.extend({
                  format: "dropdown",
                  sticky: false
              }, options);
              return this.each(function() {
                  $(this).find(".button").on('click', function(){
                      $(this).toggleClass('menu-opened');
                      var mainmenu = $(this).next('ul');
                      if (mainmenu.hasClass('open')) {
                          mainmenu.slideToggle().removeClass('open');
                      }
                      else {
                          mainmenu.slideToggle().addClass('open');
                          if (settings.format === "dropdown") {
                              mainmenu.find('ul').show();
                          }
                      }
                  });
                  cssmenu.find('li ul').parent().addClass('has-sub');
                  multiTg = function() {
                      cssmenu.find(".has-sub").prepend('<span class="submenu-button"></span>');
                      cssmenu.find('.submenu-button').on('click', function() {
                          $(this).toggleClass('submenu-opened');
                          if ($(this).siblings('ul').hasClass('open')) {
                              $(this).siblings('ul').removeClass('open').slideToggle();
                          }
                          else {
                              $(this).siblings('ul').addClass('open').slideToggle();
                          }
                      });
                  };
                  if (settings.format === 'multitoggle') multiTg();
                  else cssmenu.addClass('dropdown');
                  if (settings.sticky === true) cssmenu.css('position', 'fixed');
                  resizeFix = function() {
                      var mediasize = 1000;
                      if ($( window ).width() > mediasize) {
                          cssmenu.find('ul').show();
                      }
                      if ($(window).width() <= mediasize) {
                          cssmenu.find('ul').hide().removeClass('open');
                      }
                  };
                  resizeFix();
                  return $(window).on('resize', resizeFix);
              });
          };
      })(jQuery);

      (function($){
          $(document).ready(function(){
              $("#cssmenu").menumaker({
                  format: "multitoggle"
              });
          });
      })(jQuery);




  </script>

</head>

<body>

<%=render 'layouts/navbar'%>
<br>
<div class="container <%=controller_name %> <%= action_name %>">
   <% if flash.any?%>
      <% flash.keys.each do |key|%>
        <div class="alert alert-success alert alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <strong><%= flash[key]%></strong>
        </div>
      <%end%>
    <%end%>
  <%= yield %>

</div>
</body>
</html>